// Generated by Haxe 4.2.1
(function ($global) { "use strict";
var Lambda = function() { };
Lambda.count = function(it,pred) {
	var n = 0;
	if(pred == null) {
		var _ = $getIterator(it);
		while(_.hasNext()) {
			var _1 = _.next();
			++n;
		}
	} else {
		var x = $getIterator(it);
		while(x.hasNext()) {
			var x1 = x.next();
			if(pred(x1)) {
				++n;
			}
		}
	}
	return n;
};
var Main = function() { };
Main.main = function() {
	var countClient = function(clientId,map) {
		return Lambda.count(map,function(entry) {
			return Object.prototype.hasOwnProperty.call(entry.h,clientId);
		});
	};
	var _g = new haxe_ds_StringMap();
	var _g1 = new haxe_ds_StringMap();
	_g1.h["OSX"] = "1";
	_g1.h["QNX"] = "2";
	_g.h["Balu"] = _g1;
	var _g1 = new haxe_ds_StringMap();
	_g1.h["OSX"] = "3";
	_g.h["Tomi"] = _g1;
	var _g1 = new haxe_ds_StringMap();
	_g1.h["QNX"] = "4";
	_g.h["Zsoc"] = _g1;
	var map = _g;
	console.log("Main.hx:15:",countClient("OSX",map));
};
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.prototype = {
	iterator: function() {
		return new haxe_ds__$StringMap_StringMapValueIterator(this.h);
	}
};
var haxe_ds__$StringMap_StringMapValueIterator = function(h) {
	this.h = h;
	this.keys = Object.keys(h);
	this.length = this.keys.length;
	this.current = 0;
};
haxe_ds__$StringMap_StringMapValueIterator.prototype = {
	hasNext: function() {
		return this.current < this.length;
	}
	,next: function() {
		return this.h[this.keys[this.current++]];
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
function $getIterator(o) { if( o instanceof Array ) return new haxe_iterators_ArrayIterator(o); else return o.iterator(); }
})({});
