// Generated by Haxe 4.2.1
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/Lambda.hx",
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/usr/share/haxe/std/cpp/_std/haxe/ds/StringMap.hx",
"/usr/share/haxe/std/haxe/iterators/ArrayIterator.hx",
"Main.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/Lambda.hx",
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/usr/share/haxe/std/cpp/_std/haxe/ds/StringMap.hx",
"/usr/share/haxe/std/haxe/iterators/ArrayIterator.hx",
"/home/bkil/cache/haxe/MapCount/src/Main.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Lambda",
"Main",
"Std",
"haxe.Log",
"haxe.ds.StringMap",
"haxe.iterators.ArrayIterator",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
