// Generated by Haxe 4.2.1

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Main : global::haxe.lang.HxObject {
	
	public Main(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Main() {
		global::Main.__hx_ctor__Main(this);
	}
	
	
	protected static void __hx_ctor__Main(global::Main __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			global::haxe.lang.Function countClient = ( (( global::Main_main_5__Fun.__hx_current != null )) ? (global::Main_main_5__Fun.__hx_current) : (global::Main_main_5__Fun.__hx_current = ((global::Main_main_5__Fun) (new global::Main_main_5__Fun()) )) );
			global::haxe.ds.StringMap<object> _g = new global::haxe.ds.StringMap<object>();
			{
				global::haxe.ds.StringMap<string> _g1 = new global::haxe.ds.StringMap<string>();
				_g1.@set("OSX", "1");
				_g1.@set("QNX", "2");
				_g.@set("Balu", _g1);
			}
			
			{
				global::haxe.ds.StringMap<string> _g2 = new global::haxe.ds.StringMap<string>();
				_g2.@set("OSX", "3");
				_g.@set("Tomi", _g2);
			}
			
			{
				global::haxe.ds.StringMap<string> _g3 = new global::haxe.ds.StringMap<string>();
				_g3.@set("QNX", "4");
				_g.@set("Zsoc", _g3);
			}
			
			global::haxe.ds.StringMap<object> map = _g;
			global::haxe.Log.trace.__hx_invoke2_o(((double) (((int) (countClient.__hx_invoke2_f(default(double), "OSX", default(double), map)) )) ), global::haxe.lang.Runtime.undefined, default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"main", "Main", "Main.hx"}, new int[]{1981972957}, new double[]{((double) (15) )}));
		}
	}
	
	
}



#pragma warning disable 109, 114, 219, 429, 168, 162
public class Main_main_7__Fun : global::haxe.lang.Function {
	
	public Main_main_7__Fun(string clientId) : base(1, 0) {
		this.clientId = clientId;
	}
	
	
	public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
		global::haxe.ds.StringMap<string> entry = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::haxe.ds.StringMap<string>) (global::haxe.ds.StringMap<object>.__hx_cast<string>(((global::haxe.ds.StringMap) (((object) (__fn_float1) )) ))) )) : (((global::haxe.ds.StringMap<string>) (global::haxe.ds.StringMap<object>.__hx_cast<string>(((global::haxe.ds.StringMap) (__fn_dyn1) ))) )) );
		return entry.exists(this.clientId);
	}
	
	
	public string clientId;
	
}



#pragma warning disable 109, 114, 219, 429, 168, 162
public class Main_main_5__Fun : global::haxe.lang.Function {
	
	public Main_main_5__Fun() : base(2, 1) {
	}
	
	
	public static global::Main_main_5__Fun __hx_current;
	
	public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
		global::haxe.ds.StringMap<object> map = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((object) (__fn_float2) )) ))) )) : (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (__fn_dyn2) ))) )) );
		string clientId = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (global::haxe.lang.Runtime.toString(__fn_float1)) : (global::haxe.lang.Runtime.toString(__fn_dyn1)) );
		return ((double) (global::Lambda.count<object>(((object) (map) ), ((global::haxe.lang.Function) (new global::Main_main_7__Fun(clientId)) ))) );
	}
	
	
}


