// Generated by Haxe 4.2.1
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main_main_7__Fun extends haxe.lang.Function
{
	public Main_main_7__Fun(java.lang.String clientId)
	{
		//line 7 "/home/bkil/cache/haxe/MapCount/src/Main.hx"
		super(1, 0);
		//line 7 "/home/bkil/cache/haxe/MapCount/src/Main.hx"
		this.clientId = clientId;
	}
	
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 7 "/home/bkil/cache/haxe/MapCount/src/Main.hx"
		haxe.ds.StringMap<java.lang.String> entry = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((haxe.ds.StringMap<java.lang.String>) (((java.lang.Object) (__fn_float1) )) )) : (((haxe.ds.StringMap<java.lang.String>) (__fn_dyn1) )) );
		//line 7 "/home/bkil/cache/haxe/MapCount/src/Main.hx"
		return entry.exists(this.clientId);
	}
	
	
	public java.lang.String clientId;
	
}


